language: go
sudo: required
dist: trusty
osx_image: xcode7.3
os:
- linux
go:
- 1.6.4
- 1.7.6
- 1.8.5
- 1.9.2
- tip
before_install:
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo modprobe fuse ; sudo chmod 666 /dev/fuse ; sudo chown root:$USER /etc/fuse.conf ; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install osxfuse ; fi
install:
- git fetch --unshallow --tags
- make vars
- make build_dep
script:
- make check
- make quicktest
- make compile_all
env:
  global:
    - GOTAGS=cmount
  matrix:
    secure: gU8gCV9R8Kv/Gn0SmCP37edpfIbPoSvsub48GK7qxJdTU628H0KOMiZW/T0gtV5d67XJZ4eKnhJYlxwwxgSgfejO32Rh5GlYEKT/FuVoH0BD72dM1GDFLSrUiUYOdoHvf/BKIFA3dJFT4lk2ASy4Zh7SEoXHG6goBlqUpYx8hVA=
addons:
  apt:
    packages:
    - fuse
    - libfuse-dev
    - pkg-config
matrix:
  allow_failures:
  - go: tip
  include:
  - os: osx
    go: 1.9.2
    env: GOTAGS=""
deploy:
  provider: script
  script: make travis_beta
  on:
    branch: master
    go: 1.9.2
    condition: $TRAVIS_OS_NAME == linux
